---
- name: Adjust ownership of tmpdir
  file:
    path: "{{ tmpdir_path }}"
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"

- stat: path=~/teamviewer
  register: teamviewer
  become: yes
  become_user: "{{ primary_user }}"

- name: Download TeamViewer
  get_url:
    url: https://download.teamviewer.com/download/teamviewer_i386.tar.xz
    dest: "{{ tmpdir_path }}/teamviewer_i386.tar.xz"
  when: not teamviewer.stat.exists
  become: yes
  become_user: "{{ primary_user }}"

- name: Install TeamViewer
  command: tar xvfJ "{{ tmpdir_path }}/teamviewer_i386.tar.xz"
  when: not teamviewer.stat.exists
  become: yes
  become_user: "{{ primary_user }}"
