---
- stat: path=~/teamviewer
  register: teamviewer
  become: yes
  become_user: "{{ primary_user }}"

- name: Install TeamViewer
  unarchive:
    src: https://download.teamviewer.com/download/teamviewer_i386.tar.xz
    # Can't use ~ as dest
    dest: "/home/{{ primary_user }}"
    remote_src: yes
  when: not teamviewer.stat.exists
  become: yes
  become_user: "{{ primary_user }}"

- name: Install dpi tweak
  template:
    src: dpi.reg.j2
    dest: ~/teamviewer/tv_bin/script/dpi.reg
  become: yes
  become_user: "{{ primary_user }}"

- name: Patch dpi tweak
  patch:
    src: tvw_profile_legacy.patch
    # Can't use ~ as dest
    dest: "/home/{{ primary_user }}/teamviewer/tv_bin/script/tvw_profile_legacy"
  become: yes
  become_user: "{{ primary_user }}"

- name: Install desktop icon
  copy:
    src: teamviewer.desktop
    dest: ~/Desktop
  become: yes
  become_user: "{{ primary_user }}"
