---
- name: Add projects share
  lineinfile:
    dest: /etc/crouton/shares
    regexp: ^encrypted/projects ~/projects$
    line: encrypted/projects ~/projects

- name: Check git push configuration
  command: git config --get --global push.default
  register: gitconfig_push
  changed_when: false
  failed_when: false
  ignore_errors: yes
  sudo: yes
  sudo_user: "{{ primary_user }}"

- name: Configure git
  command: git config --global push.default simple
  sudo: yes
  sudo_user: "{{ primary_user }}"
  when: gitconfig_push.stdout != 'simple'

- name: Install libxss1 (missing from Atom's dependencies)
  apt:
    update-cache: yes
    name: libxss1
    state: present

- name: Check if Atom is installed
  command: dpkg-query -l atom
  register: atom_installed
  changed_when: false
  failed_when: false
  ignore_errors: yes

- name: Download Atom
  # Use wget(1) instead because Python in jessie is too old to support
  # SNI, causing the download to fail
  command: wget -nv -O /tmp/atom.deb https://atom.io/download/deb
  when: atom_installed.stderr.find('no packages found') != -1

- name: Install Atom
  apt: deb=/tmp/atom.deb
  when: atom_installed.stderr.find('no packages found') != -1

- name: Install Atom packages
  command: apm install {{ item }} creates=~/.atom/packages/{{ item }}
  with_items:
    - auto-detect-indentation
    - highlight-selected
    - minimap
    - open-recent
    - todo-show
  sudo: yes
  sudo_user: "{{ primary_user }}"

- name: Install Atom configuration
  copy: src=config.cson dest=~/.atom/config.cson
  sudo: yes
  sudo_user: "{{ primary_user }}"

- name: Install programming languages
  apt:
    update-cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - ruby

- name: Install tools
  apt:
    update-cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - httpie
    - jq
