---
- name: Add projects share
  lineinfile:
    dest: /etc/crouton/shares
    regexp: ^encrypted/projects ~/projects$
    line: encrypted/projects ~/projects

- name: Install libxss1 (missing from Atom's dependencies)
  apt:
    update-cache: yes
    name: libxss1
    state: present

- name: Check if Atom is installed
  command: dpkg-query -l atom
  register: atom_installed

- name: Download Atom
  get_url:
    url: https://atom.io/download/deb
    dest: "{{ tmpdir_path }}/atom.deb"
  when: atom_installed.stdout.find('no packages found') != -1
