---
- name: Add projects share
  lineinfile:
    dest: /etc/crouton/shares
    regexp: ^encrypted/projects ~/projects$
    line: encrypted/projects ~/projects

# TODO: Make this not cause a change every time
- name: Configure git
  command: git config --global push.default simple
  sudo: yes
  sudo_user: "{{ primary_user }}"

- name: Install libxss1 (missing from Atom's dependencies)
  apt:
    update-cache: yes
    name: libxss1
    state: present

- name: Check if Atom is installed
  command: dpkg-query -l atom
  register: atom_installed
  changed_when: false
  failed_when: false
  ignore_errors: yes

- name: Download Atom
  # Use wget(1) instead because Python in jessie is too old to support
  # SNI, causing the download to fail
  command: wget -nv -O /tmp/atom.deb https://atom.io/download/deb
  when: atom_installed.stderr.find('no packages found') != -1
