---
- name: Add projects share
  lineinfile:
    dest: /etc/crouton/shares
    regexp: ^encrypted/projects ~/projects$
    line: encrypted/projects ~/projects

- name: Install ca-certificates (needed for get_url)
  apt:
    update-cache: yes
    name: ca-certificates
    state: present

- name: Install libxss1 (missing from Atom's dependencies)
  apt:
    update-cache: yes
    name: libxss1
    state: present

- name: Check if Atom is installed
  command: dpkg-query -l atom
  register: atom_installed
  ignore_errors: yes

- name: Download Atom
  get_url:
    url: https://atom.io/download/deb
    dest: /tmp/atom.deb
  when: atom_installed.stderr.find('no packages found') != -1
