---
- name: Install locales
  apt:
    update-cache: yes
    name: locales
    state: present

- name: Generate en_US.UTF-8 locale
  command: locale-gen --lang en_US.UTF-8
  args:
    creates: /usr/lib/locale/locale-archive

- name: Install mksh
  apt:
    update-cache: yes
    name: mksh
    state: present
