---
- name: Install locales
  apt:
    update-cache: yes
    name: locales
    state: present

- name: Update locale-gen configuration
  lineinfile:
    dest: /etc/locale.gen
    regexp: ^# en_US\.UTF-8 UTF-8$
    line: en_US.UTF-8 UTF-8
    backrefs: yes
  register: localegen

- stat: path=/usr/lib/locale/locale-archive
  register: localearchive

- name: Generate en_US.UTF-8 locale
  command: locale-gen --lang en_US.UTF-8
  when: localegen.changed or not localearchive.stat.exists

- stat: path=/etc/crouton/xserverrc-local.example
  register: xserverrclocalexample
- stat: path=/etc/crouton/xserverrc-local
  register: xserverrclocal

- name: Copy xserverrc-local.example
  command: cp /etc/crouton/xserverrc-local.example /etc/crouton/xserverrc-local
  when: xserverrclocalexample.stat.exists and not xserverrclocal.stat.exists

- stat: path=/etc/crouton/xserverrc-local
  register: xserverrclocal

- name: Adjust DPI of xserver
  lineinfile:
    dest: /etc/crouton/xserverrc-local
    regexp: ^#?XARGS="\$XARGS\s+-dpi\s+
    line: XARGS="$XARGS -dpi {{ xserver_dpi }}x{{ xserver_dpi }}"
  when: xserverrclocal.stat.exists

- name: Add Backups share
  lineinfile:
    dest: /etc/crouton/shares
    regexp: ^encrypted/Backups ~/Backups$
    line: encrypted/Backups ~/Backups

- name: Install mksh
  apt:
    update-cache: yes
    name: mksh
    state: present

- name: Remove BASH configuration
  file: path=~/{{ item }} state=absent
  with_items:
    - .bash_profile
    - .bashrc
    - .bash_history
    - .bash_logout
  sudo: yes
  sudo_user: "{{ primary_user }}"

- name: Set shell of primary user
  user: name="{{ primary_user }}" shell=/bin/mksh

- name: Install mksh configuration
  copy: src={{ item.src }} dest=~/{{ item.dest }}
  with_items:
    - { src: 'dot.profile', dest: '.profile' }
    - { src: 'dot.mkshrc', dest: '.mkshrc' }
  sudo: yes
  sudo_user: "{{ primary_user }}"
- name: Install vim
  apt:
    update-cache: yes
    name: vim
    state: present

- name: Install vim configuration
  copy: src={{ item.src }} dest=~/{{ item.dest }}
  with_items:
    - { src: 'dot.vimrc', dest: '.vimrc' }
    - { src: 'dot.vim/uri-ref-20061101.vim', dest: '.vim/' }
    - { src: 'dot.vim/indent/mail.vim', dest: '.vim/indent/' }
  sudo: yes
  sudo_user: "{{ primary_user }}"

- name: Install less
  apt:
    update-cache: yes
    name: less
    state: present
